import 'package:bharat_bhraman_app/Screens/statedetailsscreen.dart';
import 'package:bharat_bhraman_app/models/states.dart';
import 'package:flutter/material.dart';

class StateScreen extends StatelessWidget {
  StateScreen({Key key}) : super(key: key);
  var state_list = [
    States(
        imageurl:
            'https://i.pinimg.com/originals/cf/6c/e7/cf6ce7c4f5221d22a4dbe956366b10f3.gif',
        title: 'Andhra Pradesh',
        area: '1,60,205 Sq. Kms',
        population: '49.67 Million(2011)',
        capital: 'Amaravati',
        state: true,
        cm: 'Sri Y.S. Jagan Mohan Reddy',
        language: 'Telugu'),
    States(
        imageurl: 'https://knowindia.gov.in/assets/images/img-haryana1.jpg',
        title: 'Haryana',
        area: '44,212 sq.km',
        population: '2,53,53,081',
        capital: 'Chandigarh',
        state: true,
        cm: 'Manohar Lal Khattar',
        language: 'Hindi, Punjabi'),
    States(
        imageurl: 'https://knowindia.gov.in/assets/images/img-manipur1.jpg',
        title: 'Manipur',
        area: '22,327 sq.km',
        population: '27,21,756',
        capital: 'Imphal',
        state: true,
        cm: 'N.Biren Singh',
        language: 'Meitei'),
    States(
        imageurl: 'https://knowindia.gov.in/assets/images/img-sikkim1.jpg',
        title: 'Sikkim',
        area: '7,096 sq.km',
        population: '6,07,688',
        capital: 'Gangtok',
        state: true,
        cm: 'Prem Singh Tamang',
        language: 'Nepali, Lepcha'),
    States(
        imageurl:
            'https://knowindia.gov.in/assets/images/img-arunachal-pradesh1.jpg',
        title: 'Arunachal Pradesh',
        area: '83,743 sq.km',
        population: '13,82,611',
        capital: 'Itanagar',
        state: true,
        cm: 'Pema Khandu',
        language: 'Monpa, Miji'),
    States(
        imageurl: 'https://knowindia.gov.in/assets/images/img-himachal.jpg',
        title: 'Himachal Pradesh',
        area: '55,673 sq.km',
        population: '68,56,509',
        capital: 'Shimla',
        state: true,
        cm: 'Pema Khandu',
        language: 'Hindi'),
    States(
        imageurl: 'https://knowindia.gov.in/assets/images/img-meghalaya1.jpg',
        title: 'Meghalaya',
        area: '22,429 sq.km',
        population: '29,64,007',
        capital: 'Shillong',
        state: true,
        cm: 'Conrad Sangma',
        language: 'Khasi, English'),
    States(
      imageurl: 'https://knowindia.gov.in/assets/images/img-tamilnadu1.jpg',
      title: 'Tamil Nadu',
      area: '1,30,058',
      population: '7,21,38,958',
      capital: 'Chennai',
      state: true,
      cm: 'Edappadi K. Palaniswami',
      language: 'Tamil, English',
    ),
    States(
        imageurl: 'https://knowindia.gov.in/assets/images/img-assam1.jpg',
        title: 'Assam',
        area: '78,438 sq.km',
        population: '3,11,69,272',
        capital: 'Dispur',
        state: true,
        cm: 'Sarbananda Sonowal',
        language: 'Assamese, Bengali'),
    States(
        imageurl: 'https://knowindia.gov.in/assets/images/img-jharkhand1.jpg',
        title: 'Jharkhand',
        area: '79,714 sq. km',
        population: '3,11,69,272',
        capital: 'Ranchi',
        state: true,
        cm: 'Hemant Soren',
        language: 'Hindi, Angika'),
    States(
        imageurl: 'https://knowindia.gov.in/assets/images/img-mizoram1.jpg',
        title: 'Mizoram',
        area: '21,081 sq. km',
        population: '10,91,014 ',
        capital: 'Aizawl',
        state: true,
        cm: 'Zoramthanga',
        language: 'Mizo, Hindi'),
    States(
        imageurl: 'https://d-maps.com/m/asia/india/telangana/telangana48.gif',
        title: 'Telangana',
        area: '112,077 Sq. Kms',
        population: '350.04 Lakhs',
        capital: 'Hyderabad',
        state: true,
        cm: 'K. Chandrashekar Rao',
        language: 'Telugu, Urdu'),
    States(
        imageurl: 'https://knowindia.gov.in/assets/images/img-bihar1.jpg',
        title: 'Bihar',
        area: '94,163 sq. km',
        population: '10,38,04,637',
        capital: 'Patna',
        state: true,
        cm: 'Nitish Kumar',
        language: 'Hindi, Urdu'),
    States(
        imageurl: 'https://knowindia.gov.in/assets/images/img-karnataka1.jpg',
        title: 'Karnataka',
        area: '1,91,791 sq. km',
        population: '6,11,30,704 ',
        capital: 'Bangalore',
        state: true,
        cm: 'B.S. Yediyurappa',
        language: 'Kannada'),
    States(
        imageurl: 'https://knowindia.gov.in/assets/images/img-nagaland.jpg',
        title: 'Nagaland',
        area: '16,579 sq. km',
        population: '19,80,602 ',
        capital: 'Kohima',
        state: true,
        cm: 'Neiphiu Rio',
        language: 'Nagamese, English'),
    States(
        imageurl: 'https://knowindia.gov.in/assets/images/img-tripura1.jpg',
        title: 'Tripura',
        area: '10,491.69 km.sq',
        population: '36,71,032 ',
        capital: 'Agartala',
        state: true,
        cm: 'Biplab Kumar Dev',
        language: 'Kokborok, Bengali'),
    States(
        imageurl: 'https://knowindia.gov.in/assets/images/img-chhatisgarh1.jpg',
        title: 'Chhattisgarh',
        area: '1,36,034 sq. km',
        population: '2,55,40,196 ',
        capital: 'Raipur',
        state: true,
        cm: 'Bhupesh Baghel',
        language: 'Chhattisgarhi, Hindi'),
    States(
        imageurl: 'https://knowindia.gov.in/assets/images/img-kerala1.jpg',
        title: 'Kerala',
        area: '38,863 sq. km',
        population: '3,33,87,677 ',
        capital: 'Thiruvanathapuram',
        state: true,
        cm: 'Pinarayi Vijayan',
        language: 'Malayalam, English'),
    States(
        imageurl: 'https://knowindia.gov.in/assets/images/img-orissa1.jpg',
        title: 'Odisha',
        area: '1,55,707 sq. km',
        population: '4,19,47,358',
        capital: 'Bhubaneshwar',
        state: true,
        cm: 'Naveen Patnaik',
        language: 'Odia'),
    States(
        imageurl: 'https://knowindia.gov.in/assets/images/img-uttaranchal1.jpg',
        title: 'Uttarakhand',
        area: '53,484 sq. km',
        population: '1,01,16,752',
        capital: 'Dehradun',
        state: true,
        cm: 'Trivendra Singh Rawat',
        language: 'Trivendra Singh Rawat'),
    States(
        imageurl: 'https://knowindia.gov.in/assets/images/img-goa1.jpg',
        title: 'Goa',
        area: '3,702 sq. km',
        population: '14,57,723',
        capital: 'Panaji',
        state: true,
        cm: 'Pramod Sawant',
        language: 'Konkani'),
    States(
        imageurl:
            'https://knowindia.gov.in/assets/images/img-madhyapardesh.jpg',
        title: 'Madhya Pradesh',
        area: '3,08,000 sq. km',
        population: '7,25,97,565 ',
        capital: 'Bhopal',
        state: true,
        cm: 'Shivraj Singh Chouhan',
        language: 'Hindi'),
    States(
        imageurl: 'https://knowindia.gov.in/assets/images/img-punjab.jpg',
        title: 'Punjab',
        area: '50,362 sq. km',
        population: '2,77,04,236',
        capital: 'Chandigarh',
        state: true,
        cm: 'Amarindar Singh',
        language: 'Punjabi'),
    States(
        imageurl:
            'https://knowindia.gov.in/assets/images/img-uttar-pradesh1.jpg',
        title: 'Uttar Pradesh',
        area: '2,40,928 sq. km',
        population: '19,95,81,477',
        capital: 'Lucknow',
        state: true,
        cm: 'Yogi Adityanath',
        language: 'Hindi, Urdu'),
    States(
        imageurl: 'https://knowindia.gov.in/assets/images/img-gujrat1.jpg',
        title: 'Gujarat',
        area: '1,96,024 sq. km',
        population: '6,03,83,628',
        capital: 'Gandhi Nagar',
        state: true,
        cm: 'Vijay Rupani',
        language: 'Gujarati, Hindi'),
    States(
        imageurl: 'https://knowindia.gov.in/assets/images/img-maharashtra1.jpg',
        title: 'Maharashtra',
        area: '3,07,713 sq. km',
        population: '11,23,72,972',
        capital: 'Mumbai',
        state: true,
        cm: 'Uddhav Thackeray',
        language: 'Marathi'),
    States(
        imageurl: 'https://knowindia.gov.in/assets/images/img-rajasthan1.jpg',
        title: 'Rajasthan',
        area: '3,42,239 sq. km',
        population: '6,86,21,012 ',
        capital: 'Jaipur',
        state: true,
        cm: 'Ashok Gehlot',
        language: 'Rajasthani, Hindi'),
    States(
        imageurl: 'https://knowindia.gov.in/assets/images/img-west-bengal1.jpg',
        title: 'West Bengal',
        area: '88,752 sq. km',
        population: '9,13,47,736',
        capital: 'Kolkata',
        state: true,
        cm: 'Mamata Banerjee',
        language: 'Bengali, Hindi'),
    States(
        imageurl: 'https://knowindia.gov.in/assets/images/img-andaman.jpg',
        title: 'Andaman & Nicobar Islands',
        area: '8,249 sq. km',
        population: '3,79,944',
        capital: 'Port Blair',
        state: false,
        cm: 'Chetan Bhushan Sanghi',
        language: 'Hindi, Telugu'),
    States(
        imageurl: 'https://knowindia.gov.in/assets/images/img-dadra.jpg',
        title: 'Dadra and Nagar Haveli',
        area: '	491 sq km',
        population: '3,42,853',
        capital: 'Silvassa',
        state: false,
        cm: 'NA',
        language: 'Hindi, Gujarati'),
    States(
        imageurl:
            'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Kashmir_Region_November_2019.jpg/375px-Kashmir_Region_November_2019.jpg',
        title: 'Jammu & Kashmir',
        area: '222,236 sq.km',
        population: '12,267,013',
        capital: 'Srinagar',
        state: false,
        cm: 'NA',
        language: 'Kashmiri'),
    States(
        imageurl: 'https://knowindia.gov.in/assets/images/img-lakshadweep.jpg',
        title: 'Lakshadweep',
        area: '32 sq. km',
        population: '64,429',
        capital: 'Kavaratti',
        state: false,
        cm: 'NA',
        language: 'Jesseri, Malayalam'),
    States(
        imageurl: 'https://knowindia.gov.in/assets/images/img-chandigarh.jpg',
        title: 'Chandigarh',
        area: '114 sq km',
        population: '10,54,686',
        capital: 'Chandigarh',
        state: false,
        cm: 'NA',
        language: 'Hindi, Punjabi'),
    States(
        imageurl: 'https://knowindia.gov.in/assets/images/img-delhi.jpg',
        title: 'Government of NCT of Delhi',
        area: '1,483 sq. km',
        population: '1,67,53,235',
        capital: 'Delhi',
        state: false,
        cm: 'Arvind Kejriwal',
        language: 'Hindi'),
    States(
        imageurl:
            'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Kashmir_Region_November_2019.jpg/375px-Kashmir_Region_November_2019.jpg',
        title: 'Ladakh',
        area: '59,146 km.sq',
        population: '274,289',
        capital: 'Leh',
        state: false,
        cm: 'NA',
        language: 'Ladakhi, Hindi'),
    States(
        imageurl: 'https://knowindia.gov.in/assets/images/img-pondicherry.jpg',
        title: 'Puducherry',
        area: '479 sq km',
        population: '12,44,464 ',
        capital: 'Puducherry',
        state: false,
        cm: 'V. Narayanasamy',
        language: 'Tamil, Malayalam'),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("State/UTs"),
      ),
      body: ListView.builder(
        itemCount: state_list.length,
        itemBuilder: (ctx, i) {
          return ListTile(
            onTap: () {
              Navigator.of(context).push(MaterialPageRoute(
                  builder: (ctx) => StatedetailsScreen(
                        title: state_list[i].title,
                        population: state_list[i].population,
                        area: state_list[i].area,
                        capital: state_list[i].capital,
                        imageUrl: state_list[i].imageurl,
                        cm: state_list[i].cm,
                        language: state_list[i].language,
                      )));
            },
            title: Text(state_list[i].title),
            subtitle: Text(
              "(${state_list[i].capital})",
              style: TextStyle(fontSize: 12, color: Colors.pink),
            ),
            leading: ClipRRect(
              borderRadius: BorderRadius.circular(50),
              child: Image.network(
                state_list[i].imageurl,
                fit: BoxFit.fill,
                height: 50,
                width: 50,
              ),
            ),
          );
        },
      ),
    );
  }
}
